import os

Import('env')

target = '#/bin/simpletextpreprocess' + env['PROGSUFFIX']
env.Alias('simpletextpreprocess', target)

pathBoost  = os.environ['BOOST_DIR'];
cppflags = env['cxx_debug']
cppflags.extend(['-fno-strict-aliasing',
                 '-std=c++11'])
cppflags.extend(env['gccWarningFlags'])
cppflags.extend(['-isystem', pathBoost + '/include'])

sourcepaths = ['#/src']

ldflags = env['ldflags']

libpaths = []
libs = []
cppMain = [Glob('simpletextpreprocess.cpp') +
           Glob('#/src/util/StringUtil.cpp')]

simpletextpreprocess = env.Program(target, cppMain,
                                   LIBS = libs,
                                   LINKFLAGS = ldflags,
                                   LIBPATH  = libpaths,
                                   CPPFLAGS = cppflags,
                                   CPPPATH  = sourcepaths);
Default(simpletextpreprocess)
