import os

Import('env')

target = env['base_exec_dir'] + '/simpletextpreprocess' + env['PROGSUFFIX']
env.Alias('simpletextpreprocess', target)

pathBoost  = os.environ['BOOST_DIR'];
cppflags = ['-fno-strict-aliasing',
            '-std=c++11']
cppflags.extend(env['gccWarningFlags'])
cppflags.extend(['-isystem', pathBoost + '/include'])

sourcepaths = ['#/src']

libpaths = []
libs = []
cppMain = [Glob('simpletextpreprocess.cpp') +
           Glob('#/src/util/StringUtil.cpp')]

simpletextpreprocess = env.Program(target, cppMain,
                                   LIBS = libs,
                                   LIBPATH  = libpaths,
                                   CPPFLAGS = cppflags,
                                   CPPPATH  = sourcepaths);
Default(simpletextpreprocess)
