#!/bin/bash

msg="Could not find"
[[ ! -x `which ndk-build` ]]   && echo "$msg android ndk." && exit
[[ ! -x `which android` ]]     && echo "$msg android sdk." && exit
[[ ! -x `which sdl2-config` ]] && echo "$msg SDL2 dir."    && exit

export SDK_HOME=`which android | sed 's/\/tools.*//g'`
export NDK_HOME=`which ndk-build | sed 's/\/ndk-build//g'`
SDLPATH=`sdl2-config --prefix | sed 's/sdl2-x86/SDL/g'`
# SDLPATH=Path-to-SDL-source-directory
[[ ! -d $SDLPATH ]] && \
    echo "Error. Manually configure SDLPATH variable" && exit

# Create symbolic link to SDL source path
[[ ! -e ./jni/SDL ]] && ln -s $SDLPATH ./jni/SDL

# Create the local.properties file, with the path to the sdk
m="# This file is automatically generated by initialize_project.sh
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
sdk.dir=$SDK_HOME
target=android-19
"
echo "$m" > ./project.properties
