#!/bin/bash

msg="Could not find"
[[ ! -x `which ndk-build` ]]   && echo "$msg android ndk." && exit
[[ ! -x `which android` ]]     && echo "$msg android sdk." && exit
[[ ! -x `which sdl2-config` ]] && echo "$msg SDL2 dir."    && exit

export SDK_HOME=`which android | sed 's/\/tools.*//g'`
export NDK_HOME=`which ndk-build | sed 's/\/ndk-build//g'`
SDLPATH=`sdl2-config --prefix | sed 's/sdl2-x86/SDL/g'`
SDLIMAGEPATH=`sdl2-config --prefix | sed 's/sdl2-x86/SDL_image/g'`
SDLMIXERPATH=`sdl2-config --prefix | sed 's/sdl2-x86/SDL_mixer/g'`
BULLETPATH=(`pkg-config bullet --variable=prefix`-*)

# SDLPATH=Path-to-SDL-source-directory
# SDLIMAGEPATH=Path-to-SDL_image-source-directory
# SDLMIXERPATH=Path-to-SDL_mixer-source-directory
# BULLETPATH=Path-to-bullet-source-directory
[[ ! -d $SDLPATH ]] && \
    echo "Error. Manually configure SDLPATH variable" && exit
[[ ! -d $SDLIMAGEPATH ]] && \
    echo "Error. Manually configure SDLIMAGEPATH variable" && exit
[[ ! -d $SDLMIXERPATH ]] && \
    echo "Error. Manually configure SDLMIXERPATH variable" && exit
[[ ! -d $BULLETPATH ]] && \
    echo "Error. Manually configure BULLETPATH variable" && exit

# Create symbolic link to SDL source path
[[ ! -e ./jni/SDL ]] && ln -s $SDLPATH ./jni/SDL
[[ ! -e ./jni/SDL_image ]] && ln -s $SDLIMAGEPATH ./jni/SDL_image
[[ ! -e ./jni/SDL_mixer ]] && ln -s $SDLMIXERPATH ./jni/SDL_mixer
[[ ! -e ./jni/bullet ]] && ln -s $BULLETPATH ./jni/bullet

# Create the local.properties file, with the path to the sdk
m="# This file is automatically generated by initialize_project.sh
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
sdk.dir=$SDK_HOME
target=android-19
"
echo "$m" > ./project.properties
