#!/bin/bash

msg="Could not find"
[[ ! -x `which ndk-build` ]]   && echo "$msg android ndk." && exit
[[ ! -x `which android` ]]     && echo "$msg android sdk." && exit
[[ ! -x `which sdl2-config` ]] && echo "$msg SDL2 dir."    && exit

export SDK_HOME=`which android | sed 's/\/tools.*//g'`
export NDK_HOME=`which ndk-build | sed 's/\/ndk-build//g'`
PATH_SDL=`sdl2-config --prefix | sed 's/sdl2-x86/SDL/g'`
PATH_SDL_IMAGE=`sdl2-config --prefix | sed 's/sdl2-x86/SDL_image/g'`
PATH_SDL_MIXER=`sdl2-config --prefix | sed 's/sdl2-x86/SDL_mixer/g'`
PATH_SDL_TTF=`sdl2-config --prefix | sed 's/sdl2-x86/SDL_ttf/g'`
BULLET_PATH=(`pkg-config bullet --variable=prefix`-*)

# PATH_SDL=Path-to-SDL-source-directory
# PATH_SDL_IMAGE=Path-to-SDL_image-source-directory
# PATH_SDL_MIXER=Path-to-SDL_mixer-source-directory
# PATH_SDL_TTF=Path-to-SDL_ttf-source-directory
# BULLET_PATH=Path-to-bullet-source-directory
[[ ! -d $PATH_SDL ]] && \
    echo "Error. Manually configure PATH_SDL variable" && exit
[[ ! -d $PATH_SDL_IMAGE ]] && \
    echo "Error. Manually configure PATH_SDL_IMAGE variable" && exit
[[ ! -d $PATH_SDL_MIXER ]] && \
    echo "Error. Manually configure PATH_SDL_MIXER variable" && exit
[[ ! -d $PATH_SDL_TTF ]] && \
    echo "Error. Manually configure PATH_SDL_TTF variable" && exit
[[ ! -d $BULLET_PATH ]] && \
    echo "Error. Manually configure BULLET_PATH variable" && exit

# Create symbolic link to SDL source path
[[ ! -e ./jni/SDL ]]        && ln -s $PATH_SDL       ./jni/SDL
[[ ! -e ./jni/SDL_image ]]  && ln -s $PATH_SDL_IMAGE ./jni/SDL_image
[[ ! -e ./jni/SDL_mixer ]]  && ln -s $PATH_SDL_MIXER ./jni/SDL_mixer
[[ ! -e ./jni/SDL_ttf ]]    && ln -s $PATH_SDL_TTF   ./jni/SDL_ttf
[[ ! -e ./jni/bullet-src ]] && ln -s $BULLET_PATH    ./jni/bullet-src

# Create the local.properties file, with the path to the sdk
m="# This file is automatically generated by initialize_project.sh
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
#
sdk.dir=$SDK_HOME
target=android-19
"
echo "$m" > ./project.properties
