import os

Import('env')

target =  env['base_exec_dir'] + '/obj2cobj' + env['PROGSUFFIX']
env.Alias('obj2cobj', target)

pathBoost  = os.environ['BOOST_DIR'];
cppflags = ['-fno-strict-aliasing',
            '-std=c++11']
cppflags.extend(env['gccWarningFlags'])
cppflags.extend(['-isystem', pathBoost + '/include'])

sourcepaths = ['#/src']

libpaths = []
libs = []
cppMain = [Glob('obj2cobj.cpp') +
           Glob('#/src/util/CObjUtil.cpp') +
           Glob('#/src/util/StringUtil.cpp') +
           Glob('#/src/extern/tiny_obj_loader.cpp')]

obj2cobj = env.Program(target, cppMain,
                       LIBS = libs,
                       LIBPATH  = libpaths,
                       CXXFLAGS = cppflags,
                       CPPPATH  = sourcepaths);
Default(obj2cobj)
